language: python

python:
  - 3.9.6

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python -m black . --check
  - python -m flake8 . --max-line-length=88
  - python -m coverage run --source='.' manage.py test

after_success:
  - python -m coveralls